// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlSNJ8d-KHLoBmJmpS3g-Amp1eh6ujH0',
    appId: '1:281049577365:web:88742cd0c6d1438d2b689c',
    messagingSenderId: '281049577365',
    projectId: 'educontrol-v3',
    authDomain: 'educontrol-v3.firebaseapp.com',
    storageBucket: 'educontrol-v3.firebasestorage.app',
    measurementId: 'G-33ZB9E3VWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecYGFCwVZW_G8bs9EePDtumeJrQMjj90',
    appId: '1:281049577365:android:5e96daed9551781f2b689c',
    messagingSenderId: '281049577365',
    projectId: 'educontrol-v3',
    storageBucket: 'educontrol-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzubeDH3LZbtQ1HcF2kV9u_ypsaIzJHmo',
    appId: '1:281049577365:ios:a85a17d884e1b4482b689c',
    messagingSenderId: '281049577365',
    projectId: 'educontrol-v3',
    storageBucket: 'educontrol-v3.firebasestorage.app',
    iosClientId: '281049577365-2eu20l103s7ntokat068gnq5m08hf079.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEscolar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzubeDH3LZbtQ1HcF2kV9u_ypsaIzJHmo',
    appId: '1:281049577365:ios:a85a17d884e1b4482b689c',
    messagingSenderId: '281049577365',
    projectId: 'educontrol-v3',
    storageBucket: 'educontrol-v3.firebasestorage.app',
    iosClientId: '281049577365-2eu20l103s7ntokat068gnq5m08hf079.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEscolar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDlSNJ8d-KHLoBmJmpS3g-Amp1eh6ujH0',
    appId: '1:281049577365:web:384c136921dec9ca2b689c',
    messagingSenderId: '281049577365',
    projectId: 'educontrol-v3',
    authDomain: 'educontrol-v3.firebaseapp.com',
    storageBucket: 'educontrol-v3.firebasestorage.app',
    measurementId: 'G-NCDSFHDE1W',
  );

}